<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
?>
<?php
/**
 * @see FireGento_GermanSetup_Block_Imprint_Content
 */
?>

<?php if (strlen(trim($this->getBankAccount())) || strlen(trim($this->getSwift()))): ?>
    <h3>Bankverbindung</h3>
<?php endif ?>

<?php if (strlen(trim($this->getBankAccountOwner()))): ?>
    <?php echo $this->__('Account owner') ?>: <?php echo $this->getBankAccountOwner() ?><br/>
<?php endif ?>
<?php if (strlen(trim($this->getBankAccount()))): ?>
    <?php echo $this->__('Account') ?>: <?php echo $this->getBankAccount() ?><br/>
<?php endif ?>
<?php if (strlen(trim($this->getBankCodeNumber()))): ?>
    <?php echo $this->__('Bank number') ?>: <?php echo $this->getBankCodeNumber() ?><br/>
<?php endif ?>
<?php if (strlen(trim($this->getBankName()))): ?>
    <?php echo $this->__('Bank name') ?>: <?php echo $this->getBankName() ?><br/>
<?php endif ?>
<?php if (strlen(trim($this->getSwift()))): ?>
    <?php echo $this->__('SWIFT') ?>: <?php echo $this->getSwift() ?><br/>
<?php endif ?>
<?php if (strlen(trim($this->getIban()))): ?>
    <?php echo $this->__('IBAN') ?>: <?php echo $this->getIban() ?><br />
<?php endif ?>
