<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
?>
<?php
/**
 * @see FireGento_GermanSetup_Block_Imprint_Content
 */
?>
<p><strong><?php echo $this->getShopName() ?></strong></p>

<p>
    <?php echo $this->getCompanyFirst() ?><br />
    <?php if(strlen(trim($this->getCompanySecond()))): ?>
        <?php echo $this->getCompanySecond() ?><br />
    <?php endif ?>
    <?php echo $this->getStreet() ?><br />
    <?php echo $this->getZip() ?> <?php echo $this->getCity() ?>
</p>

<p>
    <?php if (strlen(trim($this->getTelephone()))): ?>
        <?php echo $this->__('Telephone') ?>: <?php echo $this->getTelephone() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getFax()))): ?>
    <?php echo $this->__('Fax') ?>: <?php echo $this->getFax() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getWeb()))): ?>
    <?php echo $this->__('Web') ?>: <a href="http://<?php echo $this->getWeb() ?>" title="<?php echo $this->getCompanyFirst() ?>"><?php echo $this->getWeb() ?></a><br />
    <?php endif ?>
    <?php echo $this->__('E-Mail') ?>: <a href="mailto:<?php echo $this->getEmail() ?>" title="<?php echo $this->getCompanyFirst() ?>"><?php echo $this->getEmail() ?></a>
</p>

<p>
    <?php if (strlen(trim($this->getFinancialOffice()))): ?>
        <?php echo $this->__('Financial office') ?>: <?php echo $this->getFinancialOffice() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getTaxNumber()))): ?>
        <?php echo $this->__('Tax number') ?>: <?php echo $this->getTaxNumber() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getVatId()))): ?>
        <?php echo $this->__('VAT-ID') ?>: <?php echo $this->getVatId() ?><br />
    <?php endif ?>
</p>

<p>
    <?php if (strlen(trim($this->getCeo()))): ?>
        <?php echo $this->__('CEO') ?>: <?php echo $this->getCeo() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getOwner()))): ?>
        <?php echo $this->__('Owner') ?>: <?php echo $this->getOwner() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getCourt()))): ?>
        <?php echo $this->__('Register court') ?>: <?php echo $this->getCourt() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getRegisterNumber()))): ?>
        <?php echo $this->__('Register number') ?>: <?php echo $this->getRegisterNumber() ?><br />
    <?php endif ?>
    <?php if (strlen(trim($this->getBusinessRules()))): ?>
        <?php echo $this->__('Reference for business rules') ?>: <?php echo $this->getBusinessRules() ?>
    <?php endif ?>
</p>

<p>
    <?php if (strlen(trim($this->getBankAccountOwner()))): ?>
        <?php echo $this->__('Account owner') ?>: <?php echo $this->getBankAccountOwner() ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($this->getBankAccount()))): ?>
        <?php echo $this->__('Account') ?>: <?php echo $this->getBankAccount() ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($this->getBankCodeNumber()))): ?>
        <?php echo $this->__('Bank number') ?>: <?php echo $this->getBankCodeNumber() ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($this->getBankName()))): ?>
        <?php echo $this->__('Bank name') ?>: <?php echo $this->getBankName() ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($this->getSwift()))): ?>
        <?php echo $this->__('SWIFT') ?>: <?php echo $this->getSwift() ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($this->getIban()))): ?>
        <?php echo $this->__('IBAN') ?>: <?php echo $this->getIban() ?><br />
    <?php endif ?>
</p>
