<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * @category  FireGento
 * @package   FireGento_MageSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013-2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>
<?php
/**
 * @var $this FireGento_MageSetup_Block_Imprint_Content
 */
?>
<?php if (strlen(trim($this->getFinancialOffice()))): ?>
    <?php echo $this->__('Financial office') ?>: <?php echo $this->getFinancialOffice() ?><br />
<?php endif ?>
<?php if (strlen(trim($this->getTaxNumber()))): ?>
    <?php echo $this->__('Tax number') ?>: <?php echo $this->getTaxNumber() ?><br />
<?php endif ?>
<?php if (strlen(trim($this->getVatId()))): ?>
    <?php echo $this->__('VAT-ID') ?>: <?php echo $this->getVatId() ?><br />
<?php endif ?>
