<div class="content-header">
    <h3><?php echo $this->__('Recommended Extensions') ?></h3>
    <p class="form-buttons"></p>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Recommended Extensions') ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset fieldset-wide" id="group_fields7">
		<div class="hor-scroll">
    		<table cellspacing="0" class="form-list">
        		<tbody>
                	<tr><td class="value" colspan="2"><strong>Deutsches Sprachpaket</strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/413/" target="_blank">http://www.magentocommerce.com/extension/413/</a></td>
                    </tr>
                    <tr>
                    	<td class="label"><label for="name">Extension Key</label></td>
                    	<td class="value">http://connect20.magentocommerce.com/community/Locale_Mage_community_de_DE</td>
                    </tr>
                    <tr><td colspan="2">&nbsp;</td></tr>

                	<tr><td class="value" colspan="2"><strong>NoState - Bundesland/Kanton entfernen</strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/8047/" target="_blank">http://www.magentocommerce.com/extension/8047/</a></td>
                    </tr>
                    <tr>
                    	<td class="label"><label for="name">Extension Key</label></td>
                    	<td class="value">http://connect20.magentocommerce.com/community/Dsdata_NoState</td>
                    </tr>
                    <tr><td colspan="2">&nbsp;</td></tr>
				</tbody>
    		</table>
		</div>
	</div>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Popular Payment Methods in Germany') ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset fieldset-wide" id="group_fields7">
		<div class="hor-scroll">
    		<table cellspacing="0" class="form-list">
        		<tbody>
                	<tr><td class="value" colspan="2"><strong>Bankeinzug/Lastschrift</strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/676/" target="_blank">http://www.magentocommerce.com/extension/676/</a></td>
                    </tr>
                    <tr>
                    	<td class="label"><label for="name">Extension Key</label></td>
                    	<td class="value">http://connect20.magentocommerce.com/community/DebitPayment</td>
                    </tr>
                    <tr><td colspan="2">&nbsp;</td></tr>

                	<tr><td class="value" colspan="2"><strong>Nachnahme</strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/454/" target="_blank">http://www.magentocommerce.com/extension/454/</a></td>
                    </tr>
                    <tr>
                    	<td class="label"><label for="name">Extension Key</label></td>
                    	<td class="value">http://connect20.magentocommerce.com/community/CashOnDelivery</td>
                    </tr>
                    <tr><td colspan="2">&nbsp;</td></tr>

                	<tr><td class="value" colspan="2"><strong>Vorkasse</strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/304/" target="_blank">http://www.magentocommerce.com/extension/304/</a></td>
                    </tr>
                    <tr>
                    	<td class="label"><label for="name">Extension Key</label></td>
                    	<td class="value">http://connect20.magentocommerce.com/community/BankPayment</td>
                    </tr>
                    <tr><td colspan="2">&nbsp;</td></tr>
				</tbody>
    		</table>
		</div>
	</div>
</div>
