<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2011 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.4.0
 */
?>
<?php
/**
 * @see FireGento_GermanSetup_Block_Adminhtml_Germansetup
 */
?>

<div class="page-head">
    <h3><?php echo $this->__('German Setup') ?></h3>
</div>

<div id="messages">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getMessageHtml() ?>
</div>

<p><?php echo $this->__('Please choose:') ?></p>
<form action="<?php echo $this->getPostActionUrl() ?>" method="get" id="form-validate">
    <fieldset class="group-select wide">
        <ul>
            <li>
                <div class="input-box">
                    <input type="checkbox" name="cms" id="checkbox_cms" value="1" checked="checked" />
                    <label for="checkbox_cms"><?php echo $this->__('Create CMS Pages and Blocks') ?></label>
                </div>
                <div class="input-box">
                    <input type="checkbox" name="email" id="checkbox_email" value="1" checked="checked" />
                    <label for="checkbox_email"><?php echo $this->__('Create Email Templates') ?></label>
                </div>
                <div class="input-box">
                    <input type="checkbox" name="tax" id="checkbox_tax" value="1" checked="checked" />
                    <label for="checkbox_tax"><?php echo $this->__('Configure Tax') ?></label>
                </div>
            </li>
        </ul>
    </fieldset>

    <div class="button-set">
        <button class="form-button" type="submit"><span><?php echo $this->__('Submit') ?></span></button>
    </div>
</form>
