<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * @category  FireGento
 * @package   FireGento_MageSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="page-title test">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name"><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" <?php if (Mage::helper('magesetup/contacts')->isEmailRequired()): ?>class="required"><em>*</em<?php endif; ?>><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text <?php if (Mage::helper('magesetup/contacts')->isEmailRequired()): ?>required-entry <?php endif; ?>validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone" <?php if (Mage::helper('magesetup/contacts')->isTelephoneRequired()): ?>class="required"><em>*</em<?php endif; ?>><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="input-text <?php if (Mage::helper('magesetup/contacts')->isTelephoneRequired()): ?>required-entry <?php endif; ?>" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
            <?php if (Mage::helper('magesetup/contacts')->isAcceptAgreement()): ?>
                <li>
                    <div class="input-box">
                        <label for="accept-agreement">
                            <input name="accept-agreement" id="accept-agreement" title="" value="" class="input-checkbox validate-required-accept-agreement" type="checkbox" >
                            <?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('I agree that my contact details are saved permanently for allocation and any further queries.')) ?>
                        </label>
                    </div>
                    <strong>
                        <?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Notice')); ?>:
                    </strong>
                    <?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('You can revoke this agreement at any time and for the future by sending an e-mail to %s.', Mage::getStoreConfig('contacts/email/recipient_email'))); ?>
                </li>
            <?php endif; ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    Validation.addAllThese([
        ['validate-required-accept-agreement', '<?php echo $this->__('Please accept the agreement or call us.'); ?>', function (v,elm) {
            var input = $$('input[name="' + elm.name.replace(/([\\"])/g, '\\$1') + '"]');
            var error = 1;

            if (input[0].type == 'checkbox' && input[0].checked == true) {
                error = 0;
            }

            if (Validation.isOnChange && input[0].type == 'checkbox') {
                Validation.reset(input[0]);
            }

            if (error == 0) {
                return true;
            } else {
                return false;
            }
        }]
    ]);
//]]>
</script>
